apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: shopmicro

data:

  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ShopMicro</title>
        <link rel="stylesheet" href="style.css">
    </head>

    <body>

    <div class="container">

        <h1>ShopMicro</h1>

        <div class="card">
            <h2>Products</h2>
            <button>Carregar productes</button>
        </div>

        <div class="card">
            <h2>Comprar producte</h2>

            <form>
                <label>Product ID</label>
                <input type="text" placeholder="ID del producte">

                <label>Quantitat</label>
                <input type="number" placeholder="Quantitat">

                <button type="submit">Comprar</button>
            </form>
        </div>

    </div>

    </body>
    </html>


  style.css: |
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f8;
        margin: 0;
        padding: 0;
    }

    .container {
        width: 500px;
        margin: 50px auto;
    }

    h1 {
        text-align: center;
        margin-bottom: 30px;
    }

    .card {
        background: white;
        padding: 20px;
        margin-bottom: 20px;
        border-radius: 8px;
        box-shadow: 0px 2px 10px rgba(0,0,0,0.1);
    }

    input {
        width: 100%;
        padding: 8px;
        margin: 5px 0 10px 0;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    button:hover {
        background-color: #0056b3;
    }
