apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-conf
  namespace: shopmicro
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      resolver 10.96.0.10 valid=5s;

      server {
        listen 80;

        # Autenticació i registre
        location /api/auth/ {
          proxy_pass http://user-service:5000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        # Llistat d'usuaris (admin)
        location /api/users {
          proxy_pass http://user-service:5000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        # Productes (públic per GET, autenticat per POST/PUT/DELETE)
        location /api/products {
          proxy_pass http://product-service:5000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        # Comandes
        location /api/orders {
          proxy_pass http://order-service:5000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        # Frontend (catch-all)
        location / {
          proxy_pass http://frontend:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
