events {}

http {
  upstream product_service { server product-service:5000; }
  upstream order_service   { server order-service:5001; }
  upstream user_service    { server user-service:5002; }

  server {
    listen 80;

    location /api/products {
      proxy_pass http://product_service/products;
    }

    location /api/orders {
      proxy_pass http://order_service/orders;
    }

    location /api/users/register {
      proxy_pass http://user_service/register;
    }

    location /api/users/login {
      proxy_pass http://user_service/login;
    }
  }
}
